# Generated by Django 6.0.4 on 2026-04-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alunos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aulas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AulaDoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_final', models.DateTimeField(blank=True, null=True)),
                ('presenca', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aula_do_aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('duracao', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id_especialidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especialidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspecialidadesDoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_competencia', models.CharField(blank=True, max_length=50, null=True)),
                ('anos_experiencia', models.IntegerField(blank=True, null=True)),
                ('certificado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especialidades_do_professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id_instrumento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instrumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(blank=True, null=True)),
                ('ano_letivo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'pagamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_contratacao', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('capacidademax', models.IntegerField(blank=True, db_column='capacidademax', null=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAula',
            fields=[
                ('id_tipoaula', models.AutoField(db_column='id_tipoaula', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipoaula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id_tipoinstrumento', models.AutoField(db_column='id_tipoinstrumento', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipoinstrumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('nome_turma', models.CharField(blank=True, max_length=50, null=True)),
                ('ano_letivo', models.IntegerField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'turmas',
                'managed': False,
            },
        ),
    ]
